server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  #dados da conexão com o banco
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://mwhyudkujjynqe:28b57d31626bd447e42705b08fd334b70a970191226cf5cdcef94e64502da2da@ec2-3-217-219-146.compute-1.amazonaws.com:5432/dccspqqcecc6lj
    username: mwhyudkujjynqe
    password: 28b57d31626bd447e42705b08fd334b70a970191226cf5cdcef94e64502da2da
  #diretivas do jpa
  jpa:
    show-sql: true
    #explicita o dialeto do banco de dados que o spring vai usar
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    #comandos abaixo são para criar coisas automaticas no bd
    generate-ddl: true
    hibernate:
      ddl-auto: none
application:
  description: projeto criado para bootcamp santander no git / Backend